apiVersion: v1
kind: Service
metadata:
  name: client-svc
spec:
  selector:
    app: client-app
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-app
  template:
    metadata:
      labels:
        app: client-app
    spec:
      containers:
        - name: client
          image: ujjwal200119/todo-app:client-app2
          ports:
            - containerPort: 3000


