apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  initContainers:
    - name: nslookup-installer
      image: alpine:latest
      command: ["sh", "-c", "apk update && apk add --no-cache bind-tools && touch /tmp/done"]
  containers:
    - name: main-container
      image: nginx:latest
      ports:
        - containerPort: 80
      readinessProbe:
        exec:
          command:
            - "test"
            - "-f"
            - "/tmp/done"
        initialDelaySeconds: 10  # Increase this value as needed
        periodSeconds: 5
