apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-vol
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/home/ubuntu/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvclaim
spec:
  volumeName: mysql-vol
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi

