apiVersion: v1
kind: Service
metadata:
  name: server-svc
spec:
  selector:
    app: server-app
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32500
  externalIPs:
    - 198.51.100.32
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
        - name: server
          image: ujjwal200119/todo-app:server-app
          env:
            - name: MYSQL_HOST
              value: 198.51.100.32 # Service name for MySQL
            - name: MYSQL_USER
              value: ujjwal
            - name: MYSQL_PASSWORD
              value: ujjwal@204
            - name: MYSQL_DATABASE
              value: Tasks
            - name: MYSQL_PORT
              value: "3306"
          ports:
            - containerPort: 5000
